Refactor makefile and readme, midway

diff --git a/build_scripts/jstranspile b/build_scripts/jstranspile
--- a/build_scripts/jstranspile
+++ b/build_scripts/jstranspile
@@ -1,7 +1,8 @@
 #!/bin/bash
 shopt -s nullglob
-. ${CONF_FILE}
-webpack_func(){ 
+. "${ROOT_DIR}/conf/common.conf"
+OUTPUT_DIR=${ROOT_DIR}/compiled
+webpack_func(){  # also look for npx TODO
 	if [ -e ${ROOT_DIR}/build_tools/toolchain/webpack/package-lock.json ]; then
 		shopt -u nullglob
 		DEBUG_LINE=''
@@ -11,19 +12,20 @@ webpack_func(){
 		if ls -A ${ROOT_DIR}/ts/**/*.ts 2> /dev/null; then
 			shopt -s nullglob
 			pushd ${ROOT_DIR}/build_tools/toolchain/webpack/
-			sudo -E -u nobody -- npx webpack --mode "${WEBPACK_MODE}" $DEBUG_LINE --entry "${ROOT_DIR}/ts/main.ts" --output "${OUTPUT_DIR}/js/bundle.js" --config "${ROOT_DIR}/build_tools/toolchain/webpack/webpack.tsconfig.js"
+			npx webpack --mode "${WEBPACK_MODE}" $DEBUG_LINE --entry "${ROOT_DIR}/ts/main.ts" --output "${OUTPUT_DIR}/js/bundle.js" --config "${ROOT_DIR}/build_tools/toolchain/webpack/webpack.tsconfig.js"
 			popd
 		elif ls -A ${ROOT_DIR}/js/**/*.js 2> /dev/null; then
 			shopt -s nullglob
 			pushd ${ROOT_DIR}/build_tools/toolchain/webpack/
-			sudo -E -u nobody -- npx webpack --mode "${WEBPACK_MODE}" $DEBUG_LINE --entry "${ROOT_DIR}/js/main.js" --output "${OUTPUT_DIR}/js/bundle.js"
+			npx webpack --mode "${WEBPACK_MODE}" $DEBUG_LINE --entry "${ROOT_DIR}/js/main.js" --output "${OUTPUT_DIR}/js/bundle.js"
 			popd
 		else
-			return 1
+			echo "Appears there is no javascript"
+			return 0
 		fi
 		shopt -s nullglob
 	else
-		echo "Webpack not found, assuming not used."
+		echo "Webpack not found, assuming not used." 
 		return 1
 	fi
 	return 0
@@ -32,13 +34,13 @@ webpack_func(){
 tsc_func(){ 
 	if ! command -v tsc > /dev/null 2>&1; then
 		echo "To compile typescript, you're expected to install node-typescript in a normal way."
-		echo "You're using vanilla javascript?"
+		echo "You're using vanilla javascript? Peasant."
 		return
 	fi
 	echo "tsc- warning: sourceMap options untested (debugging). Should allow debugging in original"
-	echo "Typescript instead of hwat is compiled to. Definitely works with webpack"
-	sudo -E -u nobody -- mkdir -p "${OUTPUT_DIR}/js" || exit
-	sudo -E -u nobody -- tsc --inlineSourceMap --inlineSources -p "${ROOT_DIR}/ts/" --outDir "${OUTPUT_DIR}/js/"
+	echo "Typescript instead of what is compiled to. Definitely works with webpack"
+	mkdir -p "${OUTPUT_DIR}/js" || exit
+	tsc --inlineSourceMap --inlineSources -p "${ROOT_DIR}/ts/" --outDir "${OUTPUT_DIR}/js/"
 }
 if ! webpack_func; then
 	tsc_func
diff --git a/build_scripts/main b/build_scripts/main
--- a/build_scripts/main
+++ b/build_scripts/main
@@ -1,18 +1,30 @@
 #!/bin/bash
+set -e
+# Set Input Dir
 
-if sudo -E -u nobody -- command -v contate > /dev/null 2>&1; then
+. "${ROOT_DIR}/conf/common.conf"
+
+if [ -z "${1}" ]; then
+	INPUT_DIR="${ROOT_DIR}/raw"
+else
+	INPUT_DIR="${1}"
+fi
+
+
+if command -v contate > /dev/null 2>&1; then
 	CONTATE=contate
 elif [ -x ./build_tools/sources/contate/build/contate ]; then
-	CONTATE="./build_tools/sources/contate/build/contate"
+	CONTATE="${ROOT_DIR}/build_tools/sources/contate/build/contate"
 	alias contate="${CONTATE}"
 else
-	echo 'contate not found: you can install it from gihub.com/autopogo/contate or `git submodule update --init` and it can be used locally from the static_template repo'
-	exit 1
+	echo "Contate not found! Check README.md! *.contate files won't work!"
 fi
-. ${CONF_FILE}
+
 if [ ! -d "${OUTPUT_DIR}" ]; then
 	echo "Output directory doesn\'t exist"
 	exit 1
 fi
-sudo -E -u nobody -- ${CONTATE} -rc ${CONF_FILE} -o ${OUTPUT_DIR}/ raw/
-sudo -E -u nobody -- rsync -vvrit --exclude '*.contate' --exclude '.*' raw/ ${OUTPUT_DIR}/
+if [ ! -z "${CONTATE}" ]; then
+	${CONTATE} -r -o ${OUTPUT_DIR}/ ${INPUT_DIR}/
+fi
+rsync -vvrit --exclude '*.contate' --exclude '.*' ${INPUT_DIR}/ ${OUTPUT_DIR}/
